import 'package:flutter/material.dart';
import 'package:quran_station/src/core/utils/color_manager.dart';

ThemeData lightTheme = ThemeData(
  appBarTheme: const AppBarTheme(
    iconTheme: IconThemeData(color: ColorManager.black),
    centerTitle: true,
    elevation: 0,
    titleSpacing: 0,
    shape: StadiumBorder(),
    // toolbarHeight: 5.h,
    backgroundColor: ColorManager.transparent,
  ),
  applyElevationOverlayColor: false,
  brightness: Brightness.light,
  buttonTheme: const ButtonThemeData(
    alignedDropdown: false,
    colorScheme: ColorScheme(
      background: Color(0xFFFDFCFF),
      brightness: Brightness.light,
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFFDAD6),
      inversePrimary: Color(0xFF9ECAFF),
      inverseSurface: Color(0xFF2F3033),
      onBackground: Color(0xFF1A1C1E),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      onInverseSurface: Color(0xFFF1F0F4),
      onPrimary: Color(0xFFFFFFFF),
      onPrimaryContainer: Color(0xFF400011),
      onSecondary: Color(0xFFFFFFFF),
      onSecondaryContainer: Color(0xFF2D1600),
      onSurface: Color(0xFF1A1C1E),
      onSurfaceVariant: Color(0xFF43474E),
      onTertiary: Color(0xFFFFFFFF),
      onTertiaryContainer: Color(0xFF00174C),
      outline: Color(0xFF73777F),
      outlineVariant: Color(0xFFC3C7CF),
      primary: Color(0xFF922C40),
      primaryContainer: Color(0xFFFFD9DC),
      scrim: Color(0xFF000000),
      secondary: Color(0xFFDC9750),
      secondaryContainer: Color(0xFFFFDCBE),
      shadow: Color(0xFF000000),
      surface: Color(0xFFFDFCFF),
      surfaceTint: Color(0xFF0061A4),
      surfaceVariant: Color(0xFFDFE2EB),
      tertiary: Color(0xFF1E2640),
      tertiaryContainer: Color(0xFFDBE1FF),
    ),
    height: 36,
    layoutBehavior: ButtonBarLayoutBehavior.padded,
    minWidth: 88,
    padding: EdgeInsets.only(bottom: 0, left: 16, right: 16, top: 0),
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.only(
        bottomLeft: Radius.elliptical(2, 2),
        bottomRight: Radius.elliptical(2, 2),
        topLeft: Radius.elliptical(2, 2),
        topRight: Radius.elliptical(2, 2),
      ),
      side: BorderSide(color: Color(0xFF000000), width: 0),
    ),
    textTheme: ButtonTextTheme.normal,
  ),
  canvasColor: const Color(0xFFFDFCFF),
  cardColor: const Color(0xFFFDFCFF),
  colorScheme: const ColorScheme(
    background: Color(0xFFFDFCFF),
    brightness: Brightness.light,
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFFDAD6),
    inversePrimary: Color(0xFF9ECAFF),
    inverseSurface: Color(0xFF2F3033),
    onBackground: Color(0xFF1A1C1E),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    onInverseSurface: Color(0xFFF1F0F4),
    onPrimary: Color(0xFFFFFFFF),
    onPrimaryContainer: Color(0xFF400011),
    onSecondary: Color(0xFFFFFFFF),
    onSecondaryContainer: Color(0xFF2D1600),
    onSurface: Color(0xFF1A1C1E),
    onSurfaceVariant: Color(0xFF43474E),
    onTertiary: Color(0xFFFFFFFF),
    onTertiaryContainer: Color(0xFF00174C),
    outline: Color(0xFF73777F),
    outlineVariant: Color(0xFFC3C7CF),
    primary: Color(0xFF922C40),
    primaryContainer: Color(0xFFFFD9DC),
    scrim: Color(0xFF000000),
    secondary: Color(0xFFDC9750),
    secondaryContainer: Color(0xFFFFDCBE),
    shadow: Color(0xFF000000),
    surface: Color(0xFFFDFCFF),
    surfaceTint: Color(0xFF0061A4),
    surfaceVariant: Color(0xFFDFE2EB),
    tertiary: Color(0xFF1E2640),
    tertiaryContainer: Color(0xFFDBE1FF),
  ),
  dialogBackgroundColor: const Color(0xFFFDFCFF),
  disabledColor: const Color(0x61000000),
  dividerColor: const Color(0xFF1F1A1C1E),
  focusColor: const Color(0x1F000000),
  highlightColor: const Color(0xFF66BCBCBC),
  hintColor: const Color(0x99000000),
  hoverColor: const Color(0x0A000000),
  iconTheme: const IconThemeData(color: Color(0xDD000000)),
  indicatorColor: const Color(0xFFFFFFFF),
  inputDecorationTheme: const InputDecorationTheme(
    alignLabelWithHint: false,
    filled: false,
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    isCollapsed: false,
    isDense: false,
  ),
  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
  platform: TargetPlatform.windows,
  primaryColor: const Color(0xFF922C40),
  primaryColorDark: const Color(0xFF1976D2),
  primaryColorLight: const Color(0xFFBBDEFB),
  primaryIconTheme: const IconThemeData(color: Color(0xFFFFFFFF)),
  primaryTextTheme: const TextTheme(
    bodyLarge: TextStyle(
      color: Color(0xFFFFFFFF),
      decoration: TextDecoration.none,
      fontFamily: 'Segoe UI',
      fontSize: 16,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    // Continue with other text styles...
  ),
  scaffoldBackgroundColor: const Color(0xFFFDFCFF),
  secondaryHeaderColor: const Color(0xFFE3F2FD),
  shadowColor: const Color(0xFF000000),
  splashColor: const Color(0xFF66C8C8C8),
  splashFactory: InkSplash.splashFactory,
  textTheme: const TextTheme(
    bodyLarge: TextStyle(
      color: Color(0xDD000000),
      decoration: TextDecoration.none,
      fontFamily: 'Segoe UI',
      fontSize: 16,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    // Continue with other text styles...
  ),
  unselectedWidgetColor: const Color(0x8A000000),
  useMaterial3: false,
  visualDensity: VisualDensity.compact,
);
