
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGw0m9IYClYhhOLQlEvYErrRqifL6-vw',
    appId: '1:40169069178:android:c4c2b2a1cd13c7f89b79c3',
    messagingSenderId: '40169069178',
    projectId: 'quran-station-f943f',
    storageBucket: 'quran-station-f943f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeTI0pt1zp8jMnJSKATxZaOn2LCS2Sn1k',
    appId: '1:40169069178:ios:3373a6d24156cb699b79c3',
    messagingSenderId: '40169069178',
    projectId: 'quran-station-f943f',
    storageBucket: 'quran-station-f943f.appspot.com',
    iosBundleId: 'com.example.quranStation',
  );
}
/*
Mahmoud Atef
El-Minya, Egypt
mahmoud.atef.work@gmail.com
+20 1080154358

HR Department

Dear Hiring Manager,

I am writing to express my interest in the Flutter Developer position advertised by Giza Systems. With proven experience in developing advanced mobile applications using Flutter, and a strong understanding of the full mobile development lifecycle, I am confident in my ability to contribute effectively to your team.

My professional background includes over two years of experience in mobile app development, with a focus on Flutter and Dart. I have successfully designed, developed, and maintained several applications across various domains, including religious, educational, health, and retail sectors. Notably, I developed the “Kalam Rabbey” application, which has received a perfect 5-star rating on Google Play and provides a comprehensive Quranic experience for users.

At my current position, I collaborate with cross-functional teams to define, design, and implement new features, ensuring that our applications are both robust and user-friendly. I am proficient in working with third-party libraries and APIs, and I have experience with unit testing code to ensure usability and reliability. Additionally, my familiarity with RESTful APIs, version control systems, and backend integration with Firebase, makes me well-suited for the responsibilities outlined in your job posting.

I pride myself on my strong problem-solving skills and ability to troubleshoot issues efficiently. I am committed to continuous learning and improvement, regularly staying updated with the latest trends and technologies in mobile development. I am confident that my background, skills, and enthusiasm for mobile app development would make me a valuable addition to the Giza Systems team.

I am excited about the opportunity to contribute to the development and maintenance of the AigentsX mobile application and to work with your international team to deliver innovative solutions. Thank you for considering my application. I look forward to the opportunity to discuss how my skills and experiences align with your needs.

Sincerely,
mahmoud atef
 */